name: Deploy Snek!
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Snek!
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v6
      - name: Set up a Node.js environment
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: 22
      - name: Install Node.js dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
